In [12]:
"""
Args: 

scipy.optimize.differential_evolution(func, bounds, args=(), 
strategy='best1bin', maxiter=1000, popsize=15, tol=0.01, mutation=(0.5, 1),
recombination=0.7, seed=None, callback=None, disp=False, polish=True, 
init='latinhypercube', atol=0, updating='immediate', workers=1, 
constraints=(), x0=None, *, integrality=None, vectorized=False)

"""

"\nArgs: \n\nscipy.optimize.differential_evolution(func, bounds, args=(), \nstrategy='best1bin', maxiter=1000, popsize=15, tol=0.01, mutation=(0.5, 1),\nrecombination=0.7, seed=None, callback=None, disp=False, polish=True, \ninit='latinhypercube', atol=0, updating='immediate', workers=1, \nconstraints=(), x0=None, *, integrality=None, vectorized=False)\n\n"

In [2]:
from scipy.optimize import differential_evolution
from scipy.optimize import minimize
import numpy as np
from random import sample
from numba import jit
from time import time

In [6]:
@jit
def LJ(r):
    r6 = r**6
    r12 = r6*r6
    return 4*(1/r12 - 1/r6)

@jit
def get_r_values(positions):
    """
    Returns total energy of LJ cluster.
    
    parameters: positions -- N x 3 2d-array of the (x,y,z) positions of each atom.
    return: total energy of LJ cluster.
    """
    # calculate distances between each pair of atoms (store results as r_values)
    p = positions
    r_values = []
    for i in range(len(positions)):
        for j in range(i, len(positions)):
            if i != j:
                distance = np.sqrt((p[i,0]-p[j,0])**2 + (p[i,1]-p[j,1])**2 + (p[i,2]-p[j,2])**2)
                r_values.append(p[i,0])
                
    return r_values

def get_total_energy(r_values):
    # calculate LJ energies of each distance and return the sum
    E = 0
    for r in r_values:
        E += LJ(r)
    return E

In [11]:
r_min, r_max = 1, 3
N = 5

positions = []
bounds = []

for i in range(N):
    positions.append(10 * np.random.random(3))

positions = np.asarray(positions)
r_values = get_r_values(positions)

for i in range(len(r_values)):
    bounds.append((r_min, r_max))
    
print("Positions:", positions)

total_energy = get_total_energy(r_values)

print("Total energy:", total_energy)

res = differential_evolution(get_total_energy, bounds)

print("Calculated minimum energy:", res.fun)

Positions: [[1.6325714  2.92580136 7.62850976]
 [0.93366264 1.74583957 5.12886129]
 [5.61351565 4.28405412 9.71521105]
 [5.00648675 1.69353182 3.28335227]
 [6.02935102 5.58857424 7.10981575]]
Total energy: 8.430421541694212
Calculated minimum energy: -9.999999999996064
